# Generated by Django 2.1.4 on 2018-12-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('the_movie_db_id', models.IntegerField(verbose_name='ID TMD')),
                ('data_lancamento', models.DateField(verbose_name='Data lançamento')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('imagem_poster', models.CharField(max_length=300, verbose_name='URL Poster')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'db_table': 'filme',
                'ordering': ['-data_lancamento'],
            },
        ),
    ]
